# Generated by Django 5.1.7 on 2025-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre de Habilidad')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono')),
                ('lugar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Leido')),
                ('contestado', models.BooleanField(default=False, verbose_name='Contestado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre'],
            },
        ),
    ]
