# Generated by Django 5.1.7 on 2025-06-25 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcastillocongosto', '0002_imagen_alter_contacto_fecha_alter_contacto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
