# Generated by Django 5.1.7 on 2025-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcastillocongosto', '0003_imagen_fecha_creacion_imagen_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
