# Generated by Django 5.1.3 on 2025-06-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcastillocongosto', '0004_alter_imagen_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
